### ISSUE TITLE
Broken link: "Join The Community" in header links to https://citrea.xyz/discord which is 404

### ISSUE THREAD

**Issue by GlenCooper** [chainwayxyz/citrea-docs#2]
At the top of https://docs.citrea.xyz/technical-specs/readme, "Join The Community" is linked to https://citrea.xyz/discord.  See https://archive.ph/25P9M#selection-97.0-97.18

When you click that link it goes to a Page Not Found error.  See https://archive.ph/uc2rO

It seems that the link should be updated...
FROM: https://citrea.xyz/discord
TO: https://discord.gg/citrea     (or maybe https://discord.com/invite/citrea ?)

**Comment by orkunkilic** [comment]
We fixed the issue. Thank you for pointing out 🥳
